#!/bin/sh

result=$(curl -X POST --data @munich-sportive.geojson $data http://geojsonlint.com/validate 2>/dev/null)

if [ "$result" = "{\"status\": \"ok\"}" ]; then
  echo "geoJSON is valid"
  exit 0
else
  echo "geoJSON is invalid: " + "$message"
  exit 1
fi
